// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/swine-schedules/Current.tsx": () => import("../components/mockups/swine-schedules/Current.tsx"),
  "./components/mockups/swine-schedules/DayPartLayout.tsx": () => import("../components/mockups/swine-schedules/DayPartLayout.tsx")
};
